from udh_backend.api.utils.permission_flags import _PermissionsEnum

if __name__ == '__main__':

    with open("__permission_enum_generate_generated.py", "w") as f:
        f.write("from udh_backend.utils.permission_flags import _PermissionsEnum, PermissionFlags, Flag\n\n\n")
        f.write("def generated(self: PermissionFlags):\n\t")
        f.write("# generated by udh_backend/api/utils/generate/permission_enum_generate.py\n\t")
        f.write("# version: 1.0\n\t")
        active_comment = False
        for field in _PermissionsEnum.__dict__:
            field: str

            if field.startswith("_"):
                if not field.startswith("__"):
                    f.write(f"\n\t# {field}")
                    if active_comment:
                        f.write("\n\t")
                    active_comment = True
                continue

            if active_comment:
                f.write("\n\t")
            active_comment = False

            f.write(f"self.{field} = Flag(self, _PermissionsEnum.{field})\n\t")
