# Generated by Django 4.2.10 on 2024-02-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('annotations', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('picture', models.BinaryField(blank=True, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('access', models.IntegerField()),
                ('url_shortcut', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('moderation_status', models.IntegerField()),
                ('moderation_comment', models.TextField(blank=True, null=True)),
                ('viewers_count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('login', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('avatar', models.BinaryField(blank=True, null=True)),
                ('rsa_key', models.TextField(blank=True, null=True)),
                ('roles', models.IntegerField(default=0)),
                ('google_token', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.PositiveIntegerField()),
                ('members', models.ManyToManyField(to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField()),
                ('picture', models.BinaryField(blank=True, null=True)),
                ('access', models.PositiveIntegerField()),
                ('create_date', models.DateTimeField()),
                ('topics', models.ManyToManyField(to='api.topics')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.articles')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.ManyToManyField(to='api.users'),
        ),
        migrations.AddField(
            model_name='articles',
            name='topics',
            field=models.ManyToManyField(to='api.topics'),
        ),
    ]
