# Generated by Django 4.2.10 on 2024-02-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_survey_surveys_comments_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='salt',
            field=models.TextField(default=''),
        ),
    ]
